### ISSUE TITLE
Como hago deploy de mi sitio usando Astro y GitHib Pages?

### ISSUE THREAD

**Issue by DakkuaDev** [midudev/porfolio.dev#11]
Buenas!!

Gracias MiduDev por la plantilla para el portfolio, me parece que es lo que necesito y me he animado a forkearla y editarla para mi. Sin embargo, he intentado hacer de la web sobre GitHub Pages usando la documentación de Astro:

https://docs.astro.build/en/guides/deploy/github/

He cambiado el astro.config para que apunte a mi usuario y repo:

```
import { defineConfig } from 'astro/config'

export default defineConfig({
  site: 'https://DakkuaDev.github.io',
})
```

También he configurado GitHub Actions junto worlflow con **astro.yml** para que se haga deploy automático, sin embargo el Action falla a la hora de hacer el setup con Node. 

![image](https://github.com/midudev/porfolio.dev/assets/61831013/f0820d6a-c137-4f13-af8e-2816f37dffc8)

No había desplegado antes de esta forma y ando un tanto perdido, ¿Alguien sabría decirme que me falta?

Saludos!!

**Comment by DakkuaDev** [comment]
@midudev  Te invoco a ver si puedes echarme una mano y orientarme por si existe una forma más sencilla de lograrlo. Gracias de antemano.

**Comment by GFrancV** [comment]
Hola @DakkuaDev que tal?
No soy Midu pero puedo ayudarte a solucionar tu problema. Porque no intentas usar el mismo workflow que proporciona Astro en la documentación del link que proporcionaste? En la sección [Configure a GitHub Action](https://docs.astro.build/en/guides/deploy/github/#configure-a-github-action) la documentación proporciona ya un workflow mucho más simple y corto que el que  estas usando en tu repositorio que facilita la tarea de despliegue.

**Comment by DakkuaDev** [comment]
> Hola @DakkuaDev que tal? No soy Midu pero puedo ayudarte a solucionar tu problema. Porque no intentas usar el mismo workflow que proporciona Astro en la documentación del link que proporcionaste? En la sección [Configure a GitHub Action](https://docs.astro.build/en/guides/deploy/github/#configure-a-github-action) la documentación proporciona ya un workflow mucho más simple y corto que el que estas usando en tu repositorio que facilita la tarea de despliegue.

Buenas, @GFrancV 

Es justamente lo que intento hacer. Sigo el paso a paso de Astro pero no soy capaz de resolverlo como se supone que hace...

**Comment by GFrancV** [comment]
Cual es el repositorio que estas intentando desplegar?

**Comment by DakkuaDev** [comment]
> Cual es el repositorio que estas intentando desplegar?

He sido finalmente capaz de desplegarla hoy. Gracias igualmente !! La doy por cerrada, saludos :)
